name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone linux-sgx repository
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      with:
          repository: intel/linux-sgx
          path: linux-sgx
    - name: Clone sgx-emm repository
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      with:
          path: linux-sgx/external/sgx-emm/emm_src
    - name: make
      run: cd linux-sgx/external/sgx-emm/; make

